export type Move = {
    move_id:number,
    move_category:string,
    name:string,
    type:string,
    damage_class:string,
    power:number,
    pp:number,
    accuracy:number,
    priority:number,
    status_name:string[],
    status_rank:number[],
    status_target:string,
    status_chance:number,
    ailment_name:string,
    ailment_chance:number,
    healing_amount:number,
    drain_power:number,
    description:string,
} | null;